interface=ap0
driver=nl80211
ctrl_interface=/data/vendor/wifi/hostapd/ctrl
ssid2=496e66696e697820484f542038
channel=157
ieee80211n=1
ieee80211ac=0
hw_mode=a

ignore_broadcast_ssid=0
wowlan_triggers=any

max_num_sta=10
macaddr_acl=0
accept_mac_file=/data/vendor/wifi/hostapd/accept_mac_update.conf
device_name=AndroidAP
manufacturer=MediaTek Inc.
model_name=MTK Wireless Model
model_number=66xx
serial_number=1.0
device_type=10-0050F204-5
